### ISSUE TITLE
Build scripts for VPS linux-image & linux-headers

### ISSUE THREAD

**Issue by user747** [Ysurac/openmptcprouter-vps#14]
Thank you for providing precompiled, up to date versions of these!
https://github.com/Ysurac/openmptcprouter-vps/blob/master/debian9-x86_64.sh#L69
https://github.com/Ysurac/openmptcprouter-vps/blob/master/debian9-x86_64.sh#L70

Would it be possible to add a build script for linux-image & linux-headers? Similar to https://github.com/Ysurac/openmptcprouter/blob/master/build.sh

I understand this is also fairly well documented, so it may be beyond the scope of this project at this time.
http://multipath-tcp.org/pmwiki.php/Users/DoItYourself

**Comment by Ysurac** [comment]
Kernel compilation instructions are now available here: https://github.com/Ysurac/openmptcprouter-vps/wiki/Compile-kernel

**Comment by user747** [comment]
Thanks again for instructions. 
Debian 9.8.0 doesn't seem to include make-kpkg 
make-kpkg seems to be available using stretch-backports, from kernel-package (13.018+nmu1~bpo9+1)

I'm trying make deb-pkg (also needed elfutils)

**Comment by user747** [comment]
I'm not sure what the advantage is to using make deb-pkg vs make-kpkg

I do know that make-kpkg with -j48 completes in under 5 minutes on a m5d.12xlarge instance ;)

**Comment by user747** [comment]
Here's how to get make-kpkg on Debian Stretch
`sudo echo 'deb http://deb.debian.org/debian stretch-backports main' > /etc/apt/sources.list.d/stretch-backports.list

sudo apt install kernel-package`
