### ISSUE TITLE
fail to compile kernel

### ISSUE THREAD

**Issue by dnwk** [Ysurac/openmptcprouter-vps#20]
Makefile:1102: recipe for target 'prepare-objtool' failed
make[2]: *** [prepare-objtool] Error 1
make[2]: Leaving directory '/root/mptcp'
debian/ruleset/targets/common.mk:194: recipe for target 'debian/stamp/conf/kernel-conf' failed
make[1]: *** [debian/stamp/conf/kernel-conf] Error 2
make[1]: Leaving directory '/root/mptcp'
/usr/share/kernel-package/ruleset/minimal.mk:93: recipe for target 'debian/stamp/conf/minimal_debian' failed
make: *** [debian/stamp/conf/minimal_debian] Error 2
Failed to create a ./debian directory: No such file or directory at /usr/bin/make-kpkg line 970.

Any idea on why it fail to compile?

**Comment by dnwk** [comment]
error: Cannot generate ORC metadata for CONFIG_UNWINDER_ORC=y, please install libelf-dev, libelf-devel or elfutils-libelf-devel

**Comment by Ysurac** [comment]
So you know what to do ;)

**Comment by dnwk** [comment]
:) I didn't read the error message careful enough last time. I guess maybe updating the wiki page?

**Comment by Ysurac** [comment]
done
