### ISSUE TITLE
config.json question

### ISSUE THREAD

**Issue by user747** [Ysurac/openmptcprouter-vps#21]
Change to 1 does not seem to add -v to ss-server
["verbose":0,](https://github.com/Ysurac/openmptcprouter-vps/blob/616cb5c4944a1cf648133195bb702c7cadb5f50d/config.json#L9)

Could not find it here
https://manpages.debian.org/testing/shadowsocks-libev/shadowsocks-libev.8.en.html

Does it work for you when setting to 1?

**Comment by user747** [comment]
Some other proposed changes -

Remove [net.ipv4.tcp_tw_recycle](https://github.com/Ysurac/openmptcprouter-vps/blob/616cb5c4944a1cf648133195bb702c7cadb5f50d/shadowsocks.conf#L23)

[This was removed since 4.12](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=4396e46187ca5070219b81773c4e65088dac50cc)

Change [net.ipv4.ip_local_port_range = 10000 65000](https://github.com/Ysurac/openmptcprouter-vps/blob/616cb5c4944a1cf648133195bb702c7cadb5f50d/shadowsocks.conf#L29)
to even and odd numbers to avoid 'ip_local_port_range: prefer different parity for start/end values'

**Comment by Ysurac** [comment]
I keep net.ipv4.tcp_tw_recycle for 4.9 kernel, but I'm not sure there is still 4.9 only OpenWrt supported platform and never made a VPS 4.9 kernel.
I modified ip_local_port_range (this was already done on router part).
