### ISSUE TITLE
Question, 2 Raspberry 1 VPS

### ISSUE THREAD

**Issue by HeLLsSs** [Ysurac/openmptcprouter-vps#25]
Hello,

I would like to know if it is possible with 2 Raspberry, connect on 2 different network, go through the VPS and allow to ping both remote network?

Schema : 

|PC 1 (192.168.100.10) ---> Raspberry ((192.168.100.1)) -> Modem1+Modem2 | --> VPS ---> Modem -> Raspberry ((192.168.100.2))-> PC2 (192.168.100.20)

How can i ping from 192.168.100.10 this computer 192.168.100.20, and access of my active directory, samba ...

Thanks in advance 👍

**Comment by Ysurac** [comment]
Not possible for now.

**Comment by HeLLsSs** [comment]
Thanks for your answer. MmM how install OpenVPN client so ?

**Comment by HeLLsSs** [comment]
Dosn't exist solution for this ? Another software ... ?

**Comment by Ysurac** [comment]
It's OpenWrt, you can install OpenVPN and configure it on both side if you want to.

**Comment by HeLLsSs** [comment]
Thanks for your fast answer :) i trying to connect on OpenVPN install server.

I download from /etc/openvpn/client
client.crt + client.key + ca.crt from server

I create .ovpn config 👍 

client
dev tun
proto tcp
;proto udp
remote XXXX 65301
resolv-retry infinite
nobind
persist-key
persist-tun
ca ca.crt
cert client.crt
key client.key
remote-cert-tls server
cipher AES-256-CBC
comp-lzo
verb 3

But impossible to connect :/

Thu Nov 07 01:29:40 2019 TLS Error: client->client or server->server connection attempted from [AF_INET]212.83.146.147:65301
Thu Nov 07 01:29:40 2019 Fatal TLS error (check_tls_errors_co), restarting

You know why ? Thanks :)

**Comment by HeLLsSs** [comment]
Thanks for your fast answer :) i trying to connect on OpenVPN install server.

I download from /etc/openvpn/client
client.crt + client.key + ca.crt from server

I create .ovpn config 👍

client
dev tun
proto tcp
;proto udp
remote XXXX 65301
resolv-retry infinite
nobind
persist-key
persist-tun
ca ca.crt
cert client.crt
key client.key
remote-cert-tls server
cipher AES-256-CBC
comp-lzo
verb 3

But impossible to connect :/

Thu Nov 07 01:29:40 2019 TLS Error: client->client or server->server connection attempted from [AF_INET]XXX:65301
Thu Nov 07 01:29:40 2019 Fatal TLS error (check_tls_errors_co), restarting

You know why ? Thanks :)
