### ISSUE TITLE
cant install vps scripts 

### ISSUE THREAD

**Issue by wttat** [Ysurac/openmptcprouter-vps#27]
Get:8 https://dl.bintray.com/multipath-tcp/mptcp_deb stable Release [2699 B]
Fetched 2699 B in 1s (1937 B/s)
Reading package lists... Done
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://repo.openmptcprouter.com stretch InRelease' doesn't support architecture 'i386'
--2019-12-01 12:09:27--  https://www.openmptcprouter.com/kernel/linux-image-4.19.80-mptcp_1.6+c62d9f6_amd64.deb
Resolving www.openmptcprouter.com (www.openmptcprouter.com)... 94.23.252.192
Connecting to www.openmptcprouter.com (www.openmptcprouter.com)|94.23.252.192|:443... 12:09:27 libtsocks(21468): Local network specification (127.0.0.1) is not validly constructed on line 20 in configuration file
connected.
HTTP request sent, awaiting response... 200 OK
Length: 37568174 (36M) [application/octet-stream]
Saving to: '/tmp/linux-image-4.19.80-mptcp_1.6+c62d9f6_amd64.deb'

/tmp/linux-image-4. 100%[===================>]  35.83M  1.82MB/s    in 17s

2019-12-01 12:09:45 (2.14 MB/s) - '/tmp/linux-image-4.19.80-mptcp_1.6+c62d9f6_amd64.deb' saved [37568174/37568174]
--2019-12-01 12:09:45--  https://www.openmptcprouter.com/kernel/linux-headers-4.19.80-mptcp_1.6+c62d9f6_amd64.deb
Resolving www.openmptcprouter.com (www.openmptcprouter.com)... 94.23.252.192
Connecting to www.openmptcprouter.com (www.openmptcprouter.com)|94.23.252.192|:443... 12:09:45 libtsocks(21473): Local network specification (127.0.0.1) is not validly constructed on line 20 in configuration file
connected.
HTTP request sent, awaiting response... 200 OK
Length: 9545288 (9.1M) [application/octet-stream]
Saving to: '/tmp/linux-headers-4.19.80-mptcp_1.6+c62d9f6_amd64.deb'

/tmp/linux-headers- 100%[===================>]   9.10M   767KB/s    in 13s

2019-12-01 12:09:59 (723 KB/s) - '/tmp/linux-headers-4.19.80-mptcp_1.6+c62d9f6_amd64.deb' saved [9545288/9545288]

Reading package lists... Done
Building dependency tree
Reading state information... Done
curl is already the newest version (7.58.0-2ubuntu3.8).
The following packages were automatically installed and are no longer required:
  linux-headers-4.15.0-54 linux-headers-4.15.0-54-generic
  linux-image-4.15.0-54-generic linux-modules-4.15.0-29-generic
  linux-modules-4.15.0-54-generic linux-modules-extra-4.15.0-54-generic
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  rename
0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.
Need to get 12.3 kB of archives.
After this operation, 37.9 kB of additional disk space will be used.
0% [Working]12:10:00 libtsocks(21490): Local network specification (127.0.0.1) is not validly constructed on line 20 in configuration file
Get:1 http://mirrors.tencentyun.com/ubuntu bionic/universe amd64 rename all 0.20-7 [12.3 kB]
Fetched 12.3 kB in 0s (0 B/s)
Selecting previously unselected package rename.
(Reading database ... 139199 files and directories currently installed.)
Preparing to unpack .../archives/rename_0.20-7_all.deb ...
Unpacking rename (0.20-7) ...
Setting up rename (0.20-7) ...
update-alternatives: using /usr/bin/file-rename to provide /usr/bin/rename (rename) in auto mode
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Install kernel linux-image-4.19.80-mptcp_1.6+c62d9f6
if kernel install fail run: dpkg --remove --force-remove-reinstreq linux-image-4.19.80-mptcp
Selecting previously unselected package linux-image-4.19.80-mptcp.
(Reading database ... 139211 files and directories currently installed.)
Preparing to unpack .../linux-image-4.19.80-mptcp_1.6+c62d9f6_amd64.deb ...
Examining /etc/kernel/preinst.d/
run-parts: executing /etc/kernel/preinst.d/intel-microcode 4.19.80-mptcp /boot/vmlinuz-4.19.80-mptcp
Done.
Unpacking linux-image-4.19.80-mptcp (1.6+c62d9f6) ...
Setting up linux-image-4.19.80-mptcp (1.6+c62d9f6) ...

 Hmm. There is a symbolic link /lib/modules/4.19.80-mptcp/build
 However, I can not read it: No such file or directory
 Therefore, I am deleting /lib/modules/4.19.80-mptcp/build

 Hmm. The package shipped with a symbolic link /lib/modules/4.19.80-mptcp/source
 However, I can not read the target: No such file or directory
 Therefore, I am deleting /lib/modules/4.19.80-mptcp/source
Running depmod.
Examining /etc/kernel/postinst.d.
run-parts: executing /etc/kernel/postinst.d/apt-auto-removal 4.19.80-mptcp /boot/vmlinuz-4.19.80-mptcp
run-parts: executing /etc/kernel/postinst.d/initramfs-tools 4.19.80-mptcp /boot/vmlinuz-4.19.80-mptcp
update-initramfs: Generating /boot/initrd.img-4.19.80-mptcp
run-parts: executing /etc/kernel/postinst.d/kdump-tools 4.19.80-mptcp /boot/vmlinuz-4.19.80-mptcp
run-parts: executing /etc/kernel/postinst.d/unattended-upgrades 4.19.80-mptcp /boot/vmlinuz-4.19.80-mptcp
run-parts: executing /etc/kernel/postinst.d/update-notifier 4.19.80-mptcp /boot/vmlinuz-4.19.80-mptcp
run-parts: executing /etc/kernel/postinst.d/x-grub-legacy-ec2 4.19.80-mptcp /boot/vmlinuz-4.19.80-mptcp
Searching for GRUB installation directory ... found: /boot/grub
Searching for default file ... found: /boot/grub/default
Testing for an existing GRUB menu.lst file ... found: /boot/grub/menu.lst
Searching for splash image ... none found, skipping ...
Found kernel: /boot/vmlinuz-4.19.55.mptcp
Found kernel: /boot/vmlinuz-4.15.0-70-generic
Found kernel: /boot/vmlinuz-4.15.0-54-generic
run-parts: /etc/kernel/postinst.d/x-grub-legacy-ec2 exited with return code 20
Failed to process /etc/kernel/postinst.d at /var/lib/dpkg/info/linux-image-4.19.80-mptcp.postinst line 391.
dpkg: error processing package linux-image-4.19.80-mptcp (--install):
 installed linux-image-4.19.80-mptcp package post-installation script subprocess returned error exit status 2
Errors were encountered while processing:
 linux-image-4.19.80-mptcp

I have tried reinstall my vps many times , but they all failed the same

**Comment by Ysurac** [comment]
Develop script, no support on this. And I don't use mptcp official repo that is added here.
And what is this i386 ? I only support x86_64 (amd64) on the VPS side.
