### ISSUE TITLE
VPS Admin scripts do not work after installation on Ubuntu Server 18.04.4

### ISSUE THREAD

**Issue by rustequal** [Ysurac/openmptcprouter-vps#28]
OS: Ubuntu Server 18.04.4 TLS.
VPS Admin Scripts: 0.1008

Steps to reproduse:

1. Install Ubuntu Server 18.04.3 TLS using the "ubuntu-18.04.3-live-server-amd64.iso" image
2. apt-get update && apt-get upgrade
3. wget -O - http://www.openmptcprouter.com/server/ubuntu18.04-x86_64.sh | sh
4. Reboot
5. Run the script:

```
# /usr/local/bin/omr-admin.py
Traceback (most recent call last):
  File "/usr/local/bin/omr-admin.py", line 22, in <module>
    from jwt import PyJWTError
ImportError: cannot import name 'PyJWTError'
```

Workaround:

Before installation you need to remove the package:
`# apt-get remove python3-jwt`

in this case, the installer will install the package:

`# pip3 install pyjwt`

and everything will work correctly ;)

**Comment by Ysurac** [comment]
This will be solved in next release. It was already fixed in dev branch, next release should be out quite soon.
