### ISSUE TITLE
(minor bug) Switch to the mptcp kernel not working through the automatic setup

### ISSUE THREAD

**Issue by dur3x** [Ysurac/openmptcprouter-vps#3]
I followed your guide: https://github.com/Ysurac/openmptcprouter/wiki/Install-the-VPS: 
```
wget -O - http://www.openmptcprouter.com/server/debian9-x86_64.sh | sh
reboot
uname -a
Linux XXXXX 4.9.87-xxxx-std-ipv6-64 #1 SMP Tue Mar 13 18:41:47 CET 2018 x86_64 GNU/Linux
```

Expected behaviour: I'm running on 4.14 kernel with mptcp support

I needed to myself modify the default kernel

**Comment by Ysurac** [comment]
This should work. What is the VPS used and what Debian version ?

**Comment by dur3x** [comment]
It's a fresh Debian 9 install on a kimsufi 2G
What I can do is to see to purpose you a fix to ensure that the grub selected is well the mptcp one

**Comment by dur3x** [comment]
Yes it was added to the grub; It's just that old one is still the default one.
Just to test the new one I can switch to this one with this command:
`grub-reboot 1`
but I don't think it's a good idea to suppose that the entry 1 is in all the cases the entry of the new one kernel (e.g. more than one existing kernel)

**Comment by Ysurac** [comment]
I will make some tests and try to find why it's not set as default on kimsufi 2G.

**Comment by dur3x** [comment]
I tested your script with a custom VM in a virtualbox; it's working perfectly. 
The problem on a kimsufi installed by ovh is that they put they own custom Kernel.
My fix purposal is just a way to ensure that we use the right Debian default kernel instead of any custom one

**Comment by Ysurac** [comment]
I don't have the same problem on my Kimsufi VPS.
What is the content of /boot ?

**Comment by Ysurac** [comment]
Last commit should solve this issue by renaming bzImage* to vmlinuz*

**Comment by dur3x** [comment]
:+1: thanks ! For me the issue can be closed; in a futur setup I will be careful if the kernel is well loaded but I'm sure it will be the case :-)
