### ISSUE TITLE
Portscans block via fail2ban + shorewall 

### ISSUE THREAD

**Issue by gnosoz** [Ysurac/openmptcprouter-vps#32]
This can be easily integrated in the vps script to further harden the configuration.

/etc/shorewall/shorewall.conf (IPv6 too) to be modified as follows to close connections also if they are established at time of firewall activation/restart:
BLACKLIST="ALL"

It requires /etc/shorewall/policy (IPv6 too) to be modified as follows:
This allows to have all logged nicely:
net             all             DROP            info

apt install fail2ban -y

echo '[Definition]
failregex = DROP.* SRC=<HOST>
ignoreregex =' | sudo tee /etc/fail2ban/filter.d/portscan.conf

echo '[portscan]
enabled  = true
filter   = portscan
logpath  = /var/log/kern.log
action   = shorewall
maxretry = 5
' | tee -a /etc/fail2ban/jail.local

On regards with the actions for shorewall there is already a set of rules perfectly working in /etc/fail2ban/action.d/shorewall.conf and no mods are needed there.

I will create a script to incorporate these modification in the vps install / update

**Comment by gnosoz** [comment]
Following up on above in just a few hours I can report the following blocks:
fail2ban-client status portscan
Status for the jail: portscan
|- Filter
|  |- Currently failed:	72
|  |- Total failed:	3084
|  `- File list:	/var/log/kern.log
`- Actions
   |- Currently banned:	28
   |- Total banned:	29

Mostly are bot scans but still I rather have them locked up :)

I will implement fail2ban in the router too and advise on config as it will have few differences

**Comment by gnosoz** [comment]
little modification after some time used I noticed that shorewall drops/logs several UDP packets requests (8-10) to port 8999 during configuration.
```
Apr 28 20:28:31 sd-163141 kernel: [683273.123021] Shorewall:net-fw:DROP:IN=enp1s0 OUT= MAC=XXXXXXXX0 SRC=XXXXXXXX DST=XXXXXXXX LEN=132 TOS=0x08 PREC=0x20 TTL=46 ID=7582 DF PROTO=UDP SPT=8999 DPT=8999 LEN=112 
Apr 28 20:28:31 sd-163141 kernel: [683273.175532] Shorewall:net-fw:DROP:IN=enp1s0 OUT= MAC=XXXXXXXX SRC=XXXXXXXX DST=XXXXXXXX LEN=132 TOS=0x08 PREC=0x20 TTL=46 ID=7601 DF PROTO=UDP SPT=8999 DPT=8999 LEN=112 
```
Increasing the maxretry to 50 DROPS and increasing the findtime did the trick to ban scanning attempt but avoid risking to have one the aggregated lines to be locked out.

**Comment by Ysurac** [comment]
I have no idea from where these UDP packets on port 8999 can come from, I don't have anything like that in my logs.

**Comment by gnosoz** [comment]
I don't know either but they where coming from each wan directly to the vps.
