### ISSUE TITLE
Problem forwarding port 9100

### ISSUE THREAD

**Issue by Corrado56** [Ysurac/openmptcprouter-vps#34]
Hi, I have a problem forwarding port 9100 (remote printer)

Open MPTCP router is 192.168.1.20
the printer is 192.168.1.17 mask 255.255.255.0 gw 192.168.1.20
Redirect all ports from server to this router is checked
Port forwarding from "VPN" to "this device" port 9100 to lan IP 192.168.1.17 port 9100 enabled (tcp and udp)
on local computer defined a IP printer with VPS ip and port 9100 raw.
When I sent a test page, the printer queue opens and I could see the document in the queue, but the printer remains silent and after some seconds the document disappears without errors. (where is going the stream ? )

192.168.1.4 is an Asus Router (wan1) where a have the same vpn forwarding rule
If I configure the printer with gw 192.168.1.4 and send the test page to the Asus router IP, the printer is printing.

**Comment by Ysurac** [comment]
Issues here are only related to VPS script, please open an issue on https://github.com/Ysurac/openmptcprouter/issues
