### ISSUE TITLE
Comment mettre à jour le VPS en 0.1018?

### ISSUE THREAD

**Issue by JeedHome44** [Ysurac/openmptcprouter-vps#35]
Bonjour,

C'est la première fois que je mets à jour OMR.
J'ai donc déjà téléchargé le version 56 pour le raspberry avec le fichier sysupdate. j'avais d'abord décompressé et j'ai vu qu'il ne fallait pas donc ça c'est bien passé.

Et là, je n'ai plus eu d'accès à Google, Facebook... j'ai donc fait un reboot du VPS. Les accès marchent de nouveaux mais je vois que le VPS propose la version 0.1018 maintenant.

Quelles sont donc les lignes de commandes à effectuer pour mettre à jour le VPS?
Je n'ai pas trouvé le réponse sur le repository de OMR ni sur le site.

Merci

**Comment by Ysurac** [comment]
De la même façon qu'une première installation : https://github.com/Ysurac/openmptcprouter/wiki/Install-or-update-the-VPS
Les clefs et configurations seront conservées.

**Comment by JeedHome44** [comment]
J'ai exécuté le script et ça n'a pas mis à jour en 0.1018
C'est toujours en 17.

De plus, la, ça bloque le site Google complètement. Je ne comprends pas comment le débloquer.

**Comment by Ysurac** [comment]
Que dit le script après exécution ? La version du script se trouve dans /etc/motd sur le VPS.
Que veut dire ça bloque le site google ?

**Comment by JeedHome44** [comment]
Ce fichier contient ça après exécution du script tout à l'heure:

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
< OpenMPTCProuter VPS 0.1017 >

**Comment by JeedHome44** [comment]
Je veux dire que si je mets google.com dans la barre de recherche, ca me dit que le site n'est pas accessible. Mais après un reboot VPS il marche. J'ai vérifié, ce n'est pas Pi-hole qui le bloque.

**Comment by Ysurac** [comment]
Et à la fin du script d'installation du VPS ?

**Comment by JeedHome44** [comment]
Je n'ai pas fait de capture.
Mais ça a mis successful mais en mentionnant la version 0.1017 et ça ne m'a pas réaffiché mes clés

**Comment by Ysurac** [comment]
Relance le, ou télécharge le en vérifiant la version dans le fichier.

**Comment by JeedHome44** [comment]
Et la je réessaie Google sur PC ou smartphone et ça me redit site inaccessible. Il est accessible seulement quand le VPS ne l'est pas.

**Comment by Ysurac** [comment]
Vu que le VPS est à jour ou dans un état étrange, ça parait normal.

**Comment by JeedHome44** [comment]
J'ai re téléchargé le fichier sur le VPS. Je le vérifie ou?

**Comment by Ysurac** [comment]
Au début du fichier, il y a "OMR_VERSION".

**Comment by JeedHome44** [comment]
J'avais 3 copies du fichier. J'ai tout supprimé et j'ai re téléchargé.
Je réinstalle la et je te dis

**Comment by JeedHome44** [comment]
Ah ça a l'air bon! Ça m'a mis la 0.1018
Je reboot et regarde si tout est ok

**Comment by JeedHome44** [comment]
Par contre Google.com inaccessible encore avec le VPS même en désactivant Pi-hole

**Comment by Ysurac** [comment]
La résolution DNS fonctionne ?

**Comment by JeedHome44** [comment]
Bon c'est une erreur de ma part c'est Pi Home qui le bloque alors que je ne veux pas... il ne le bloquait pas avant mise à jour
