### ISSUE TITLE
Wireshark et OMR?

### ISSUE THREAD

**Issue by JeedHome44** [Ysurac/openmptcprouter-vps#38]
Bonsoir,

Je souhaite capturer des paquets d'un appareils wifi sur le LAN OMR pour le domotiser sur Home Assistant.

Si j'exécute Wireshark sur le pc de bureau, il ne snife pas l'appareil même si je lance des commandes dessus depuis le serveur Mi Home.

Est-il possible d'installer Wireshark sur le Pi OMR pour tenter de snifer directement ce qu'envoie l'appareil au routeur?

Y a-t-il une solution plus fiable?

Merci

**Comment by Ysurac** [comment]
tcpdump est installé par défaut sur OpenMPTCProuter.

**Comment by JeedHome44** [comment]
C'est la même chose que Wireshark?
Comment l'utiliser?
Avec l'interface OMR?

**Comment by Ysurac** [comment]
Via SSH, il n'y a pas d'interface graphique. Possible d'enregistrer un fichier pcap visible via wireshark.

**Comment by JeedHome44** [comment]
Merci je vais donc me renseigner sur comment faire fonctionner tcpdump.

**Comment by JeedHome44** [comment]
Par contre, quels sont les logs SSH d'OMR?

**Comment by JeedHome44** [comment]
Bonjour,

OMR cache les paquets HTTP et HTTPS sur tcpdump?

J'ai fait un enregistrement et je ne vois rien en http ou https dessus.

Le dev que je dois aider pour intégrer mon WC japonais à Home assistant ne comprend pas.

Merci

**Comment by Ysurac** [comment]
Rien n'est caché. En écoutant sur l'interface LAN, eth0 le plus souvent, normalement tout est visible.

**Comment by JeedHome44** [comment]
Je fais un tcpdump -n "src host 192.168.100.160" -i any -w /tmp/capture/test.pcap et ensuite je déclenche des actions du XV pour qu'ils envoient les infos vers Mi Home mais je vois rien en http dans les paquets...
Je vais voir avec le dev.

Merci pour tes réponses.
Bonne journée
