### ISSUE TITLE
Old version of Ubuntu (18.04.4)?

### ISSUE THREAD

**Issue by milankragujevic** [Ysurac/openmptcprouter-vps#40]
Can the VPS script be used on Ubuntu 18.04.4? Architecture is amd64. I would like to avoid newer versions because this is not a VM but a bare-metal instance and newer Ubuntu versions have problems with stability and are more bloated for my taste.

**Comment by Ysurac** [comment]
Not possible. If the script is launched on 18.04 distrib will be updated to 20.04.
