### ISSUE TITLE
No UDP communication from vps (or internal) to/from outside

### ISSUE THREAD

**Issue by nitrique** [Ysurac/openmptcprouter-vps#41]
Hi,

I cannot do an iperf on UDP on the vps (or in lan) from outside, I get the following in syslog (vps) :

`Feb  5 16:15:09 omr-gateway kernel: [417691.229205] Shorewall:net-fw:DROP:IN=ens18 OUT= MAC=00:50:56:01:de:b9:2c:5a:0f:16:97:3b:08:00 SRC=163.**.**.162 DST=62.**.**.51 LEN=1498 TOS=0x00 PREC=0x00 TTL=56 ID=18204 PROTO=UDP SPT=36053 DPT=4000 LEN=1478` 

How can I disable this rule and allow communication ?

Here is the port redirection in OMR router :

<img width="692" alt="Capture d’écran 2021-02-05 à 16 17 53" src="https://user-images.githubusercontent.com/4180708/107052463-fae1f100-67cd-11eb-8ec5-31522b50a751.png">

Thanks,
Regards.

Nicolas

**Comment by Ysurac** [comment]
Redirecting all ports is not a good idea.
Check if rules are applied on the VPS: https://github.com/Ysurac/openmptcprouter/wiki/Port-forwarding#debug

**Comment by nitrique** [comment]
I have a proxmox cluster on the end with firewalls, don't need another one on vps or omr

**Comment by nitrique** [comment]
@Ysurac can you reply to the question please ?

**Comment by Ysurac** [comment]
Read the link.

**Comment by nitrique** [comment]
It does not reply to the question @Ysurac

**Comment by Ysurac** [comment]
So ask the question correctly.
But all info about VPS firewall are in the link.

**Comment by nitrique** [comment]
@Ysurac I explain the context :

I have a server with IP failovers in a datacenter

I have an OMR in another datacenter with a proxmox cluster behind

An IPfo is assigned to a local ip 10.0.100.3 via omrip1server
I need to redirect all ports in both udp and tcp to 10.0.100.3 (like a DMZ)

When I test with iperf from another server on the internet on port 4000 UDP (for example), the traffic is blocked by the firewall on the mptcp server.

How can I create a DMZ for both TCP and UDP ?

**Comment by Ysurac** [comment]
And the answer is still in the link.
You checked shorewall rules ?

**Comment by nitrique** [comment]
Problem solved using V2ray + Glorytun TCP (in OMR advanced configuration)

Shadowsocks is not stable for me (fail during docker image subset download)
With V2Ray it work with both TCP and UDP and port redirection works great.

-> NAT Reflexion should be disabled if redirecting all ports (otherwise OMR interface will not be reachable anymore)

It add only 6ms of latency.

Hope it helps other users 😊

@Ysurac if you do open-source don't be so bitter...

**Comment by Ysurac** [comment]
@nitrique when you open an issue read the answer. Really. This can help.
