### ISSUE TITLE
 error: cannot access archive 'omr-shadowsocks-libev-build-deps_3.3.4-2_all.deb': No such file or directory

### ISSUE THREAD

**Issue by hairydogltd** [Ysurac/openmptcprouter-vps#42]
When I run the install script, it fails because it can't find version 3.3.4-2 

As far as I can make out, v 3.3.5 is current, but I can't see where to fix the script

Can anyone help, please?

**Comment by hairydogltd** [comment]
or alternatively, the problem might be here:

dpkg-deb: building package 'omr-shadowsocks-libev-build-deps' in '../omr-shadowsocks-libev-build-deps_3.3.4-2_all.deb'.

The package has been created.
Attention, the package has been created in the current directory,

**Comment by Ysurac** [comment]
The package is compiled and created by the script from my shadowsocks-libev fork.
What is exactly the error you have and where ?

**Comment by hairydogltd** [comment]
The error is exactly what I pasted into the subject line

**Comment by Ysurac** [comment]
I need context. You don't have only this line.

**Comment by hairydogltd** [comment]
`Building dependency tree
Reading state information... Done
libsodium-dev is already the newest version (1.0.17-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
dh_testdir
dh_testroot
dh_prep
dh_testdir
dh_testroot
dh_install
dh_installdocs
dh_installchangelogs
dh_compress
dh_fixperms
dh_installdeb
dh_gencontrol
dh_md5sums
dh_builddeb
dpkg-deb: building package 'omr-shadowsocks-libev-build-deps' in '../omr-shadowsocks-libev-build-deps_3.3.4-2_all.deb'.

The package has been created.
Attention, the package has been created in the current directory,
not in ".." as indicated by the message above!
dpkg: error: cannot access archive 'omr-shadowsocks-libev-build-deps_3.3.4-2_all.deb': No such file or directory
mk-build-deps: dpkg --unpack failed
`

**Comment by Ysurac** [comment]
What is the distribution ?

**Comment by hairydogltd** [comment]
debian buster

**Comment by Ysurac** [comment]
I'm not able to reproduce the issue on an up to date Debian.
What is the VPS provider ?

**Comment by hairydogltd** [comment]
It's not a vps. I'm testing on a local server before trying it on a live machine

**Comment by Ysurac** [comment]
This can be a missing package that is available in most default installation.
Check above the log if you can find another error.

**Comment by hairydogltd** [comment]
I don't know where you mean to look for another error.

**Comment by Ysurac** [comment]
in the log.

**Comment by hairydogltd** [comment]
I meant that I don't know where the log is

**Comment by Ysurac** [comment]
in the console.

**Comment by hairydogltd** [comment]
There are no other errors in the console before that one.

**Comment by hairydogltd** [comment]
here's a log I made
[log.txt](https://github.com/Ysurac/openmptcprouter-vps/files/5944106/log.txt)

**Comment by hairydogltd** [comment]
This is the complete log from the console.
[omr install log.txt](https://github.com/Ysurac/openmptcprouter-vps/files/5944339/omr.install.log.txt)
I definitely can't see any errors prior to the one about being in the wrong directory.

**Comment by hairydogltd** [comment]
Is there anything more I can do to help resolve this issue?

**Comment by Ysurac** [comment]
I have no way to reproduce this issue, so I can't help.
Check your Debian 10 install, update it if needed.

**Comment by hairydogltd** [comment]
I, on the other hand, can not fail to produce this error. 
I can't really understand why a missing component would cause an error message about the wrong directory being used, but if this is possible, perhaps you could suggest what might be missing, and why it doesn't give any errors.
This is a standard HP Prolinea server running a normal version of Debian Buster, which is completely up to date. 
The only other thing I can try is to build a new box from scratch to test on. Should it work that way?
Am I wrong in assuming that it should work? Is there some special VPS component that is needed, but not available on a dedicated server?

**Comment by Ysurac** [comment]
There is no wrong directory error. You have a warning about that file is created in current directory but it's normal.
The script should work on all x86_64 Debian Buster install, it's tested on a lot of VPS and manual install. So any x86_64 install with at least 1024Mo ram and an internet connection should work.

**Comment by hairydogltd** [comment]
I tried it on a similar box, but on a brand new install of Debian netinstall with nothing added. It failed with an "invalid response" error from github, so I ran that bit manually then ran the whole thing again. It worked this time, with quite a few warnings. But it did eventually get to the end.
You're right: I got the same wrong directory warning, but the process didn't fail at that point.
The problem is that what I really wanted to know is whether I can add this to a server that is already being used for other things (it has a web server, database and a few other bits). 
The alternative plan was to see if I can add the web server, database and other bits to the VPS after it is set up, or will it need to run on its own?

**Comment by Ysurac** [comment]
It's not recommended, but possible (before or after is not a problem, if it's already a Debian 10).
You will need to open ports in shorewall by editing ```/etc/shorewall/rules``` on the VPS.

**Comment by hairydogltd** [comment]
I'm wondering if that was the problem. The server that it wouldn't install on had a firewall running. 
Perhaps the script should check for prerequisites, such as ports open, before installing?

**Comment by Ysurac** [comment]
The script only need to be able to contact ports 80 and 443.
