### ISSUE TITLE
Nessus scan

### ISSUE THREAD

**Issue by fuckFH** [Ysurac/openmptcprouter-vps#43]
A Nessus scan on the current version showed 5 medium findings.
Some of them make me a little worried.

_The following two can be easily correct by the user:_
```
SSL Certificate Cannot Be Trusted
Plugin Output
tcp/65228
The following certificate was at the top of the certificate
chain sent by the remote host, but it is signed by an unknown
certificate authority :
|-Subject : CN=server
|-Issuer : CN=ChangeMe
------------------------------------------------------------------------------------------------------------------------------------------
Plugin Output
tcp/65500/www
The following certificate was at the top of the certificate
chain sent by the remote host, but it is signed by an unknown
certificate authority :
|-Subject : C=US/ST=Oregon/L=Portland/O=OpenMPTCProuterVPS/OU=Org/CN=www.openmptcprouter.vps
|-Issuer : C=US/ST=Oregon/L=Portland/O=OpenMPTCProuterVPS/OU=Org/CN=www.openmptcprouter.vps
------------------------------------------------------------------------------------------------------------------------------------------
```
_He had only to issue new certificates to get rid of the Subject and Issuer information. The bad thing about the default Subject and Issuer information is that they are the same on all installations._

_For the next findings the developer has to cut old pigtails, or he can give us the OK to disable TLSv1 support and remove weak cipher suites, maybe when we disable the weak cipher and TLSv1 the OpenMPTCProuter cannot connect to the server?_
```
SSL Medium Strength Cipher Suites Supported (SWEET32)
Plugin Output
tcp/65228
Medium Strength Ciphers (> 64-bit and < 112-bit key, or 3DES)
Name Code KEX Auth Encryption MAC
---------------------- ---------- --- ---- --------------------- ---
ECDHE-RSA-DES-CBC3-SHA 0xC0, 0x12 ECDH RSA 3DES-CBC(168) SHA1
DES-CBC3-SHA 0x00, 0x0A RSA RSA 3DES-CBC(168) SHA1
The fields above are :
{Tenable ciphername}
{Cipher ID code}
Kex={key exchange}
Auth={authentication}
Encrypt={symmetric encryption method}
MAC={message authentication code}
{export flag}
------------------------------------------------------------------------------------------------------------------------------------------
104743 - TLS Version 1.0 Protocol Detection
Plugin Output
tcp/65228
TLSv1 is enabled and the server supports at least one cipher.
```

**Comment by Ysurac** [comment]
OpenMPTCProuter doesn't use TLS for authentication for V2Ray (port 65228) or API (port 65500) even if I can put something nicer to see. Certificates can't be trusted when VPS doesn't have a domain name (so not possible to make something that work in all cases to trust certificates).
For V2Ray, it use TLS 1.3 by default.

**Comment by fuckFH** [comment]
Nice to hear. So far I understand from your statement: Nessus misinterprets some information or the OpenMPTCProuter simulates information, which is not there. V2Ray (port 65228) and API (port 65500) use only TLS1.3 (but why you wrote in the first line that V2Ray and API don't use at all TLS?). It is perfectly clear to me that certificates are not trustful for a Nessus scan (for this application we need here no external root of trust), my point was that a bot could scan the whole Internet and identifies all openmptcprouter-vps instances around the world because they are easily identifiable with the certificate information, it is a kind of information disclosure, some randomness would be fine.

**Comment by Ysurac** [comment]
I say TLS is not use for authentication, it's used for encryption.
Yes I can use some random data, but even without using certificates it's easy to identifies that a server is an openmptcprouter-vps instances.

**Comment by gnosoz** [comment]
@fuckFH for increased security you can use following steps:
     - install fail2ban to ban any IP that sends a request to a port closed therefore preventing the OMR ports from being discovered and this adds an extra strong level of security.
     - ssh standard security upgrade (use keys no passwords, prevent root login, add line AllowUser <user>, etc..)
     - ssh block within Shorewall the access to this port from only safe IPs or bastion hosts
     - ssh usage of port knocking in case bastion host or safe IPs are not an option

@Ysurac on regards with upgrading security the omr-admin.py script doesn't seem to log anywhere the failed password requests. 
It would be great to add a few lines to this script in order to have some logs maybe in the standard /var/log/syslog for the failed attempts with the IP address and username used to authenticate as this way allow the possibility to monitor and keep track of these attempts and ban instantly any attacker

**Comment by fuckFH** [comment]
Thanks! I hope that I can provide in the future some lines of code for this great project.
