### ISSUE TITLE
It was working brilliantly. Now it isn't!

### ISSUE THREAD

**Issue by hairy-dog** [Ysurac/openmptcprouter-vps#50]
I had OMR running well, using 4G connections, with v0.57.3 on a Pi4 and what I think was the latest version on the VPS.

Whilst I was away from home, the hosting company relocated the VPS server host to a different rack. 

As far as I am aware, it was working after the move, but at some point soon after, it stopped working.

The first thing I tried was rebooting. That made no difference, so then I reimaged the server and reinstalled openmptcprouter-vps but that made no difference either!

I think this is a problem with the hosting, but I'm not sure how to work out what the problem is. How can I get more information about what is wrong?

![omr example](https://user-images.githubusercontent.com/10561885/119404804-38647e80-bcd8-11eb-8c1c-5b869c2a8c0e.png)

**Comment by hairy-dog** [comment]
Hmm. I tried setting up a VPS with a different host, and had the same problem. So perhaps the problem is not with the host.
Is there a log file that wold help work out what is wrong?

**Comment by Ysurac** [comment]
You can check log in State->System log.
Make sure VPS key if the correct one now in the wizard and valid it again.

**Comment by hairy-dog** [comment]
The logs offered no clues, so I started again, reinstalling from factory defaults. 
That was fine, so I tried to restore settings from the server, which brought the problem back. I couldn't work out what the problem was, so I started again with default settings. This time I sent the new settings to the server!
I don't know what I fixed, but it is all working nicely again.
