### ISSUE TITLE
Installation script fails, update-grub.sh

### ISSUE THREAD

**Issue by proalvo** [Ysurac/openmptcprouter-vps#51]
I am installing the OMR server on VPS (service provider is not one of tested service providers).

Installation script fails, there seems to be number of errors - I suppose the environment is missing something that is needed by script. For me that script is so cryptic that I cannot figure out what is the problem. Any idea? 

Here is the full installation log:
-----------------

Linux vps 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
root@vps:~#
root@vps:~#
root@vps:~#
root@vps:~# wget -O - https://www.openmptcprouter.com/server/debian10-x86_64.sh | sh
--2021-05-24 15:17:04--  https://www.openmptcprouter.com/server/debian10-x86_64.sh
Resolving www.openmptcprouter.com (www.openmptcprouter.com)... 95.216.70.99, 2a01:4f9:2b:69a::2
Connecting to www.openmptcprouter.com (www.openmptcprouter.com)|95.216.70.99|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 55984 (55K) [application/octet-stream]
Saving to: ‘STDOUT’

-                                 100%[=============================================================>]  54.67K  --.-KB/s    in 0.03s

2021-05-24 15:17:05 (1.72 MB/s) - written to stdout [55984/55984]

Check user...
Check Linux version...
Check architecture...
Check about broken packages...
Check if OpenMPTCProuter VPS is already installed...
Update mode
Remove lock and update packages list...
Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:2 http://deb.debian.org/debian buster InRelease [121 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:4 http://security.debian.org/debian-security buster/updates/main Sources [186 kB]
Get:5 http://security.debian.org/debian-security buster/updates/main amd64 Packages [290 kB]
Get:6 http://security.debian.org/debian-security buster/updates/main Translation-en [150 kB]
Get:7 http://deb.debian.org/debian buster/main Sources [7841 kB]
Get:8 http://deb.debian.org/debian buster-updates/main Sources.diff/Index [6640 B]
Ign:8 http://deb.debian.org/debian buster-updates/main Sources.diff/Index
Get:9 http://deb.debian.org/debian buster-updates/main amd64 Packages.diff/Index [6640 B]
Get:10 http://deb.debian.org/debian buster-updates/main Translation-en.diff/Index [4180 B]
Get:11 http://deb.debian.org/debian buster-updates/main amd64 Packages 2020-06-04-2016.16.pdiff [1101 B]
Get:12 http://deb.debian.org/debian buster-updates/main amd64 Packages 2020-06-07-1403.53.pdiff [439 B]
Get:13 http://deb.debian.org/debian buster-updates/main amd64 Packages 2020-06-13-2000.26.pdiff [552 B]
Get:14 http://deb.debian.org/debian buster-updates/main amd64 Packages 2020-10-24-2001.35.pdiff [286 B]
Get:15 http://deb.debian.org/debian buster-updates/main amd64 Packages 2020-12-24-1401.30.pdiff [286 B]
Get:16 http://deb.debian.org/debian buster-updates/main amd64 Packages 2021-01-29-2000.47.pdiff [408 B]
Get:17 http://deb.debian.org/debian buster-updates/main amd64 Packages 2021-02-07-1359.56.pdiff [2302 B]
Get:18 http://deb.debian.org/debian buster-updates/main amd64 Packages 2021-04-22-1401.14.pdiff [1996 B]
Get:19 http://deb.debian.org/debian buster-updates/main amd64 Packages 2021-04-23-1401.02.pdiff [1127 B]
Get:20 http://deb.debian.org/debian buster-updates/main Translation-en 2020-06-07-1403.53.pdiff [368 B]
Get:19 http://deb.debian.org/debian buster-updates/main amd64 Packages 2021-04-23-1401.02.pdiff [1127 B]
Get:21 http://deb.debian.org/debian buster-updates/main Translation-en 2020-06-13-2000.26.pdiff [423 B]
Get:22 http://deb.debian.org/debian buster-updates/main Translation-en 2021-02-07-1359.56.pdiff [1506 B]
Get:23 http://deb.debian.org/debian buster-updates/main Translation-en 2021-04-22-1401.14.pdiff [1408 B]
Get:23 http://deb.debian.org/debian buster-updates/main Translation-en 2021-04-22-1401.14.pdiff [1408 B]
Get:24 http://deb.debian.org/debian buster/main amd64 Packages [7907 kB]
Get:25 http://deb.debian.org/debian buster/main Translation-en [5969 kB]
Get:26 http://deb.debian.org/debian buster-updates/main Sources [4868 B]
Fetched 22.6 MB in 7s (3405 kB/s)
Reading package lists... Done
N: Repository 'http://deb.debian.org/debian buster InRelease' changed its 'Version' value from '10.4' to '10.9'
Install apt-transport-https, gnupg and openssh-server...
Reading package lists... Done
Building dependency tree
Reading state information... Done
gnupg is already the newest version (2.2.12-1+deb10u1).
openssh-server is already the newest version (1:7.9p1-10+deb10u2).
openssh-server set to manually installed.
The following packages were automatically installed and are no longer required:
  dh-python grub-pc-bin irqbalance lib32ncurses5 lib32tinfo5 libbind9-140 libdns162 libglib2.0-0 libglib2.0-data libicu57 libisc160
  libisccc140 libisccfg140 liblwres141 libnuma1 libperl5.24 libpython3.5-minimal libpython3.5-stdlib python3-distutils python3-lib2to3
  python3.5 python3.5-minimal rename runit-helper sgml-base shared-mime-info tcpd xdg-user-dirs xml-core
Use 'apt autoremove' to remove them.
The following NEW packages will be installed:
  apt-transport-https
0 upgraded, 1 newly installed, 0 to remove and 69 not upgraded.
Need to get 149 kB of archives.
After this operation, 156 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster-updates/main amd64 apt-transport-https all 1.8.2.3 [149 kB]
Fetched 149 kB in 0s (2716 kB/s)
Selecting previously unselected package apt-transport-https.
(Reading database ... 31474 files and directories currently installed.)
Preparing to unpack .../apt-transport-https_1.8.2.3_all.deb ...
Unpacking apt-transport-https (1.8.2.3) ...
Setting up apt-transport-https (1.8.2.3) ...
Add OpenMPTCProuter repo...
Explanation: Prefer OpenMPTCProuter provided packages over the Debian native ones
Package: *
Pin: origin repo.openmptcprouter.com
Pin-Priority: 1001
--2021-05-24 15:17:15--  http://repo.openmptcprouter.com/openmptcprouter.gpg.key
Resolving repo.openmptcprouter.com (repo.openmptcprouter.com)... 95.216.70.99, 2a01:4f9:2b:69a::2
Connecting to repo.openmptcprouter.com (repo.openmptcprouter.com)|95.216.70.99|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://repo.openmptcprouter.com/openmptcprouter.gpg.key [following]
--2021-05-24 15:17:15--  https://repo.openmptcprouter.com/openmptcprouter.gpg.key
Connecting to repo.openmptcprouter.com (repo.openmptcprouter.com)|95.216.70.99|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1241 (1.2K) [application/octet-stream]
Saving to: 'STDOUT'

-                                 100%[=============================================================>]   1.21K  --.-KB/s    in 0s

2021-05-24 15:17:15 (41.9 MB/s) - written to stdout [1241/1241]

OK
Install mptcp kernel and shadowsocks...
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:2 http://deb.debian.org/debian buster InRelease
Hit:3 http://deb.debian.org/debian buster-updates InRelease
Get:4 https://repo.openmptcprouter.com stretch InRelease [2122 B]
Get:5 https://repo.openmptcprouter.com stretch/main amd64 Packages [11.9 kB]
Fetched 14.0 kB in 1s (19.8 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
dirmngr is already the newest version (2.2.12-1+deb10u1).
dirmngr set to manually installed.
The following packages were automatically installed and are no longer required:
  dh-python grub-pc-bin irqbalance lib32ncurses5 lib32tinfo5 libbind9-140 libdns162 libglib2.0-0 libglib2.0-data libicu57 libisc160
  libisccc140 libisccfg140 liblwres141 libnuma1 libperl5.24 libpython3.5-minimal libpython3.5-stdlib python3-distutils python3-lib2to3
  python3.5 python3.5-minimal rename runit-helper sgml-base shared-mime-info tcpd xdg-user-dirs xml-core
Use 'apt autoremove' to remove them.
Suggested packages:
  ed diffutils-doc
The following NEW packages will be installed:
  patch
0 upgraded, 1 newly installed, 0 to remove and 68 not upgraded.
Need to get 126 kB of archives.
After this operation, 249 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main amd64 patch amd64 2.7.6-3+deb10u1 [126 kB]
Fetched 126 kB in 0s (2667 kB/s)
Selecting previously unselected package patch.
(Reading database ... 31478 files and directories currently installed.)
Preparing to unpack .../patch_2.7.6-3+deb10u1_amd64.deb ...
Unpacking patch (2.7.6-3+deb10u1) ...
Setting up patch (2.7.6-3+deb10u1) ...
Processing triggers for man-db (2.8.5-2) ...
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:2 http://deb.debian.org/debian buster InRelease
Hit:3 http://deb.debian.org/debian buster-updates InRelease
Hit:4 https://repo.openmptcprouter.com stretch InRelease
Reading package lists... Done
--2021-05-24 15:17:25--  https://www.openmptcprouter.com/kernel/linux-image-5.4.86-mptcp_1.16+9d3f35b_amd64.deb
Resolving www.openmptcprouter.com (www.openmptcprouter.com)... 95.216.70.99, 2a01:4f9:2b:69a::2
Connecting to www.openmptcprouter.com (www.openmptcprouter.com)|95.216.70.99|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 38535022 (37M) [application/octet-stream]
Saving to: '/tmp/linux-image-5.4.86-mptcp_1.16+9d3f35b_amd64.deb'

/tmp/linux-image-5.4.86-mptcp_1.1 100%[=============================================================>]  36.75M  3.88MB/s    in 9.6s

2021-05-24 15:17:35 (3.81 MB/s) - '/tmp/linux-image-5.4.86-mptcp_1.16+9d3f35b_amd64.deb' saved [38535022/38535022]

--2021-05-24 15:17:35--  https://www.openmptcprouter.com/kernel/linux-headers-5.4.86-mptcp_1.16+9d3f35b_amd64.deb
Resolving www.openmptcprouter.com (www.openmptcprouter.com)... 95.216.70.99, 2a01:4f9:2b:69a::2
Connecting to www.openmptcprouter.com (www.openmptcprouter.com)|95.216.70.99|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10035590 (9.6M) [application/octet-stream]
Saving to: '/tmp/linux-headers-5.4.86-mptcp_1.16+9d3f35b_amd64.deb'

/tmp/linux-headers-5.4.86-mptcp_1 100%[=============================================================>]   9.57M  3.84MB/s    in 2.5s

2021-05-24 15:17:38 (3.84 MB/s) - '/tmp/linux-headers-5.4.86-mptcp_1.16+9d3f35b_amd64.deb' saved [10035590/10035590]

Reading package lists... Done
Building dependency tree
Reading state information... Done
rename is already the newest version (1.10-1).
rename set to manually installed.
The following packages were automatically installed and are no longer required:
  dh-python grub-pc-bin irqbalance lib32ncurses5 lib32tinfo5 libbind9-140 libdns162 libglib2.0-0 libglib2.0-data libicu57 libisc160
  libisccc140 libisccfg140 liblwres141 libnuma1 libperl5.24 libpython3.5-minimal libpython3.5-stdlib python3-distutils python3-lib2to3
  python3.5 python3.5-minimal runit-helper sgml-base shared-mime-info tcpd xdg-user-dirs xml-core
Use 'apt autoremove' to remove them.
The following additional packages will be installed:
  git-man liberror-perl
Suggested packages:
  git-daemon-run | git-daemon-sysvinit git-doc git-el git-email git-gui gitk gitweb git-cvs git-mediawiki git-svn zip
The following NEW packages will be installed:
  curl git git-man libcurl4 liberror-perl unzip
0 upgraded, 6 newly installed, 0 to remove and 68 not upgraded.
Need to get 8053 kB of archives.
After this operation, 39.7 MB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main amd64 liberror-perl all 0.17027-2 [30.9 kB]
Get:2 http://security.debian.org/debian-security buster/updates/main amd64 libcurl4 amd64 7.64.0-4+deb10u2 [332 kB]
Get:3 http://deb.debian.org/debian buster/main amd64 git-man all 1:2.20.1-2+deb10u3 [1620 kB]
Get:4 http://security.debian.org/debian-security buster/updates/main amd64 curl amd64 7.64.0-4+deb10u2 [265 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 git amd64 1:2.20.1-2+deb10u3 [5633 kB]
Get:6 http://deb.debian.org/debian buster/main amd64 unzip amd64 6.0-23+deb10u2 [172 kB]
Fetched 8053 kB in 1s (12.8 MB/s)
Selecting previously unselected package libcurl4:amd64.
(Reading database ... 31488 files and directories currently installed.)
Preparing to unpack .../0-libcurl4_7.64.0-4+deb10u2_amd64.deb ...
Unpacking libcurl4:amd64 (7.64.0-4+deb10u2) ...
Selecting previously unselected package curl.
Preparing to unpack .../1-curl_7.64.0-4+deb10u2_amd64.deb ...
Unpacking curl (7.64.0-4+deb10u2) ...
Selecting previously unselected package liberror-perl.
Preparing to unpack .../2-liberror-perl_0.17027-2_all.deb ...
Unpacking liberror-perl (0.17027-2) ...
Selecting previously unselected package git-man.
Preparing to unpack .../3-git-man_1%3a2.20.1-2+deb10u3_all.deb ...
Unpacking git-man (1:2.20.1-2+deb10u3) ...
Selecting previously unselected package git.
Preparing to unpack .../4-git_1%3a2.20.1-2+deb10u3_amd64.deb ...
Unpacking git (1:2.20.1-2+deb10u3) ...
Selecting previously unselected package unzip.
Preparing to unpack .../5-unzip_6.0-23+deb10u2_amd64.deb ...
Unpacking unzip (6.0-23+deb10u2) ...
Setting up unzip (6.0-23+deb10u2) ...
Setting up liberror-perl (0.17027-2) ...
Setting up libcurl4:amd64 (7.64.0-4+deb10u2) ...
Setting up git-man (1:2.20.1-2+deb10u3) ...
Setting up curl (7.64.0-4+deb10u2) ...
Setting up git (1:2.20.1-2+deb10u3) ...
Processing triggers for libc-bin (2.28-10) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for mime-support (3.62) ...
Install kernel linux-image-5.4.86-mptcp_1.16+9d3f35b
 !!! if kernel install fail run: dpkg --remove --force-remove-reinstreq linux-image-5.4.86-mptcp !!!
Selecting previously unselected package linux-headers-5.4.86-mptcp.
(Reading database ... 32463 files and directories currently installed.)
Preparing to unpack .../linux-headers-5.4.86-mptcp_1.16+9d3f35b_amd64.deb ...
Unpacking linux-headers-5.4.86-mptcp (1.16+9d3f35b) ...
Setting up linux-headers-5.4.86-mptcp (1.16+9d3f35b) ...
Examining /etc/kernel/header_postinst.d.
Selecting previously unselected package linux-image-5.4.86-mptcp.
(Reading database ... 53198 files and directories currently installed.)
Preparing to unpack .../linux-image-5.4.86-mptcp_1.16+9d3f35b_amd64.deb ...
Done.
Unpacking linux-image-5.4.86-mptcp (1.16+9d3f35b) ...
Setting up linux-image-5.4.86-mptcp (1.16+9d3f35b) ...

 Hmm. There is a symbolic link /lib/modules/5.4.86-mptcp/build
 However, I can not read it: No such file or directory
 Therefore, I am deleting /lib/modules/5.4.86-mptcp/build

 Hmm. The package shipped with a symbolic link /lib/modules/5.4.86-mptcp/source
 However, I can not read the target: No such file or directory
 Therefore, I am deleting /lib/modules/5.4.86-mptcp/source

Running depmod.
Examining /etc/kernel/postinst.d.
run-parts: executing /etc/kernel/postinst.d/apt-auto-removal 5.4.86-mptcp /boot/vmlinuz-5.4.86-mptcp
run-parts: executing /etc/kernel/postinst.d/initramfs-tools 5.4.86-mptcp /boot/vmlinuz-5.4.86-mptcp
update-initramfs: Generating /boot/initrd.img-5.4.86-mptcp
W: initramfs-tools configuration sets RESUME=UUID=aa7a354f-c27d-43f5-a99f-0f1d5c90d05a
W: but no matching swap device is available.
I: The initramfs will attempt to resume from /dev/vdb
I: (UUID=b9f36bba-9a54-483a-95d0-e770ee591fde)
I: Set the RESUME variable to override this.
run-parts: executing /etc/kernel/postinst.d/zz-update-grub 5.4.86-mptcp /boot/vmlinuz-5.4.86-mptcp
Searching for GRUB installation directory ... found: /boot/grub
Searching for default file ... found: /boot/grub/default
Testing for an existing GRUB menu.lst file ... found: /boot/grub/menu.lst
Searching for splash image ... none found, skipping ...
Found kernel: /boot/vmlinuz-5.4.86-mptcp
Found kernel: /boot/vmlinuz-4.19.0-8-amd64
Updating /boot/grub/menu.lst ... done

Set MPTCP kernel as grub default...
--2021-05-24 15:18:07--  https://www.openmptcprouter.com/server/update-grub.sh
Resolving www.openmptcprouter.com (www.openmptcprouter.com)... 95.216.70.99, 2a01:4f9:2b:69a::2
Connecting to www.openmptcprouter.com (www.openmptcprouter.com)|95.216.70.99|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 746 [application/octet-stream]
Saving to: '/tmp/update-grub.sh'

/tmp/update-grub.sh               100%[=============================================================>]     746  --.-KB/s    in 0s

2021-05-24 15:18:07 (19.9 MB/s) - '/tmp/update-grub.sh' saved [746/746]

sed: can't read /boot/grub/grub.cfg: No such file or directory

**Comment by Ysurac** [comment]
Grub seems to be not installed. Are you sure you can use a custom kernel on your provider ?

**Comment by proalvo** [comment]
Thanks for prompt reply. I'll check the custom kernel issue from the service provider.

**Comment by proalvo** [comment]
Service provider confirmed that the custom kernel can be used. Any idea what I could investigate in detailed?

**Comment by Ysurac** [comment]
Check what you have in /boot/grub on the VPS.

**Comment by proalvo** [comment]
I took fresh start (with the same result) that's why menu.lst is dated today.  Here is the list of files in /boot/grub and content of the /tmp/update-grub.sh

root@omr:~# **ls -l /boot/grub**
total 1700
-rw-r--r-- 1 root root     191 May 17  2019 default
-rw-r--r-- 1 root root       0 May 17  2019 device.map
-rw-r--r-- 1 root root    8852 Oct  9  2016 e2fs_stage1_5
-rw-r--r-- 1 root root    8628 Oct  9  2016 fat_stage1_5
drwxr-xr-x 2 root root    4096 Mar 11  2019 fonts
-r--r--r-- 1 root root    5285 Mar 11  2019 grub.cfg.bak
lrwxrwxrwx 1 root root       8 Mar 11  2019 grub.conf -> menu.lst
-rw-r--r-- 1 root root    1024 Mar 11  2019 grubenv
drwxr-xr-x 2 root root   12288 Mar 11  2019 i386-pc
-rw-r--r-- 1 root root    9600 Oct  9  2016 jfs_stage1_5
drwxr-xr-x 2 root root    4096 Mar 11  2019 locale
-rw-r--r-- 1 root root    3046 May 27 20:59 menu.lst
-rw-r--r-- 1 root root    2661 May 27 20:59 menu.lst~
-rw-r--r-- 1 root root    2661 Mar  9  2020 menu.lst.kvm
-rw-r--r-- 1 root root    2661 Mar  9  2020 menu.lst.kvm_virtio
-rw-r--r-- 1 root root    2606 Mar  9  2020 menu.lst.xen
-rw-r--r-- 1 root root    8148 Oct  9  2016 minix_stage1_5
-rw-r--r-- 1 root root   10644 Oct  9  2016 reiserfs_stage1_5
-rw-r--r-- 1 root root     512 Oct  9  2016 stage1
-rw-r--r-- 1 root root  120100 Oct  9  2016 stage2
-rw-r--r-- 1 root root  120100 Oct  9  2016 stage2_eltorito
-rw-r--r-- 1 root root 1363161 Mar 11  2019 unicode.pf2
-rw-r--r-- 1 root root   10266 Oct  9  2016 xfs_stage1_5


root@omr:~# **more /tmp/update-grub.sh**
#!/bin/bash
kernel=$1
[ -z "$kernel" ] && exit 0

config_file="$(find /boot/grub* -maxdepth 1 -name grub.cfg 2>/dev/null)"
[ $config_file ] || exit 0

deflt_file="$(find /etc/default \( -name grub -o -name grub2 \) 2>/dev/null)"
[ $deflt_file ] || exit 0

#if [ -z "$(grep -m 1 vmlinuz $config_file | grep $kernel)" ]; then
        x=0
        sed -n -e 's@\([^'\"\'']*\)['\"\'']\([^'\"\'']*\).*@\1\2@' -e '/\(menuentry\) /p' <$config_file | \
                while IFS= read ln
                do
                        if [ -n "$(echo $ln | grep $kernel)" ]; then
                                x=$(expr $x - 1)
                                sed -i "s@^\(GRUB_DEFAULT=\).*@\1\"1>$x\"@" $deflt_file
                                [ -f /boot/grub/grub.cfg ] && grub-mkconfig -o /boot/grub/grub.cfg >/dev/null 2>&1
                                exit 0
                        fi
                        x=$(expr $x + 1)
                done | sed 's@\(menuentry\) @@'
#fi
root@omr:~#

**Comment by Ysurac** [comment]
It was fixed in snapshot VPS install script, but now I also fixed it in stable script.

**Comment by proalvo** [comment]
Thanks!!!!!! Now the installation script works. I continue tomorrow to finalize the router configuration.
