### ISSUE TITLE
Add Wireguard support for VPS-Kernel

### ISSUE THREAD

**Issue by SonicFM** [Ysurac/openmptcprouter-vps#54]
Currently i have Kernel 5.4.100-mptcp installed.
Sadly it is not possible to install Wireguard with this Kernel, since the DKMS-Module cannot be build, even with the MPTCP-Headers installed.

It would be great if you could enable this Kernel to function with Wireguard.

**Comment by Ysurac** [comment]
Wireguard is installed and configured by default with VPS script 0.1026, so with kernel 5.4.100-mptcp. It's used for MPTCP over VPN (when an ISP or any middle box block MPTCP).

**Comment by SonicFM** [comment]
Thanks for the quick reply!

Sry that i missed that point.

But im still curios. When i try to install the module the "normal" way (apt install -y wireguard (and thus its dependecies wireguard-tools and wireguard-dkms)) i alway get the error that the dkms-module cannot be built.

As is see in your VPS-Script you only install "wireguard-tools". If i understand that correctly, there is already the required module precompiled within your kernel, thus conflicting with dkms. Is that correct?

**Comment by Ysurac** [comment]
Yes it's correct.

**Comment by SonicFM** [comment]
Ok. Thanks for clarifying :)
I can confirm, it works as designed.
Sry, for bothering.
