### ISSUE TITLE
IP - traffic bloqué

### ISSUE THREAD

**Issue by kevimax** [Ysurac/openmptcprouter-vps#65]
Bonjour,

Je sollicite votre aide pour un problème vraiment étrange que je rencontre.

En gros, j’ai deux serveurs SIP qui se connectent a un serveur derrière l’OMR sur le port 5060, mais l'un d'entre eux m’indique que la connexion est rejetée.

Les connexion sont établies depuis les 2 IPs suivantes :

xxx.xxx.xxx.69
xxx.xxx.xxx.70

Lorsque je fais un tcpdump sur le vps et sur le routeur, je vois bien le traffic des deux IPs arriver au VPS, mais il n’y a que le traffic de l’IP finissant par 70 qui arrive au routeur.

Sur le VPS, tcpdump sur eth0 montre ques les 2 IPs arrivent, sur gt-tun0, seul 69 passe, j’en conclue donc que le traffic de 70 est bloqué au niveau du VPS.

Tout fonctionnait correctement avant que je procède à la MAJ du VPS que j’ai réalisé la semaine dernière.

J'ai procédé à une reinstallation complète du VPS et du routeur, le problème persiste (c'est là que ca devient étrange pour moi).

Pour info, le serveur SIP fait une requete environ toute les secondes pour essayer de se connecter. Je ne peux pas stopper ces requetes, le serveur etant herbergé chez une de mes prestataires. Je me suis donc demandé si, pendant la phase d'install / upgrade du VPS, il pouvait être "blacklisté" par un mechanisme pas trés content de ces connections ?? (ce qui expliquerai que le phénomène se soit produit depuis la MAJ et non pas à cause de la MAJ, vu que la reinstall n'y a rien fait).

J’ai vérifié shorewall, il me dit que l’IP est autorisée..

Je vous remercie infiniment pour votre aide!

Les VPS est en debian 10, dernière version
Routeur en v0.58.5 r0+16336-b36068d35d

**Comment by kevimax** [comment]
Merci Ysurac pour votre réponse (et votre super travail au passage !),

J'ai oulié de le préciser... C'est effectivement la première chose à laquelle j'ai pensé (fail2ban). Rien de tel n'est installé sur le VPS, je me suis rapproché de mon hébergeu (milkywan :D ) avant de poser la question ici. rien de plus de leur côté non plus.

**Comment by kevimax** [comment]
Malgré mes multiples essais avec Shorewall, je ne parviens à aucun résultat, pas même une trace de bloquage ou autre dans les logs.

Ma config actuelle est en NAT vers un pfsense, d'après la config shorewall, il semble qu'il n'y ait aucun règle spécifique de bloquage n'est-ce pas ? dois-je regarder ailleurs que dans la chaine net-vpn ?

Auriez-vous d'autre pistes à explorer à me conseiller ?

Encore merci pour votre aide

**Comment by kevimax** [comment]
Pour info : J'ai commenté SIP_HELPER dans conntrack et rechargé shorewall, sans succès.

**Comment by Ysurac** [comment]
il faut voir si la régle de redirection dans /etc/shorewall/rules est correcte. Tout le traffic entrant est bloqué par défaut.
Le traffic du VPS vers le routeur passe par le VPN.
Donc faut vérifier les régles et effectivement faire des tests avec tcpdump.

**Comment by kevimax** [comment]
Tout semble OK, d'ailleurs le reste du traffic ne pose aucun problème:

DNAT            net             vpn:$OMR_ADDR   tcp     1-64999 # OMR openmptcprouter redirect router 1-64999 port tcp
DNAT            net             vpn:$OMR_ADDR   udp     1-64999 # OMR openmptcprouter redirect router 1-64999 port udp
ACCEPT          net             $FW             tcp     65101   # OMR openmptcprouter open shadowsocks port tcp
ACCEPT          net             $FW             udp     65101   # OMR openmptcprouter open shadowsocks port udp

**Comment by kevimax** [comment]
Bonjour,

Alors, j'ai fait des logs iptables sur INPUT, traffic OK, IN OUT SRC DEST sont identiques aux autres lignes. Sur NET-VPN : rien pour cette adresse.

J'ai fait rmmod nf-conntrack-sip et rmmod nf-nat-sip et les ait ajouté a DONT_LOAD dans shorewall.conf (SIP ALG / HELPER).
Les modules sont bien désactivés, mais cela ne semblait pas être la cause :(

J'ai refait une install propre du VPS et du Routeur, toujours pareil, tout le NAT 1- 64999 fonctionne, seul 5060 pour cette adresse ne passe pas.

Je crois que j'abandonne :p :) :)

**Comment by kevimax** [comment]
Bonjour,

Il y à du nouveau de mon côté. Avec l'aide de mon prestataire, nous avons essayé d'utiliser un autre port SIP : la connexion passe.

Je conclue donc qu'une sorte de SIP ALG est actif sur shorewall, rendant le NAT OMR incertain sur certains ports concernés par des helpers.

Comme précisé plus haut, j'ai déjà essayé de commenter SIP_HELPER dans conntrack et rechargé shorewall, rmmode nf_conntrack_sip, rmmod nf_nat_sip : sans succès.

Je n'ai pas de connaissances approfondies avec shorewall / iptables. Auriez-vous une idée à explorer ?

Merci par avance.

**Comment by Ysurac** [comment]
Pour virer totalement le SIP ALG pour des tests:

```
conntrack -D -p udp --sport=5060
conntrack -D -p udp --dport=5060
modprobe -r nf_nat_sip
modprobe -r nf_conntrack_sip
```
Pour virer de façon définitive:
Dans /etc/shorewall/shorewall.conf un ```DONT_LOAD=nf_conntrack_sip``` devrait régler le soucis
Dans /etc/modprobe.d/blacklist.conf ajoutez la ligne ```blacklist nf_conntrack_sip```

**Comment by kevimax** [comment]
Merci beaucoup Yannick !

De mon côté, j'ai résolu avec :

Dans /etc/shorewall/shorewall.conf
AUTOHELPERS=No
DONT_LOAD=nf_conntrack_sip
HELPERS=none

Je pense que la manip que tu me propose et cell-ci sont équivalentes.

Tout est OK désormais !

**Comment by Ysurac** [comment]
Je vais désactiver ça par défaut.
J'ajouterais peut être plus tard une option pour l'activer/désactiver depuis la partie routeur.

**Comment by kevimax** [comment]
Je pense que c'est une bonne idée :D 

Après je ne sais pas si la plupart des utilisateur font du nat 1-64999 comme moi vers un autre firewall..., cette option peut rester necessaire si un utilisateur utilise OMR en FW et qu'il à un serveur SIP qui necessite SIP ALG (ca fait beaucoup :D :D ).

Reste le mystère sur le fait que je n'avais pas eu à faire ca avant le dernier upgrade du VPS (modif du packet shorewall probablement..).

Merci encore pour ton excellent travail. Je n'envisage plus une connexion sans OMR ! même avec de la fibre !

**Comment by kevimax** [comment]
Bonjour Yannick,

Je suis passé en 0.59, j'ai vu que la modif pour SIP ALG a été apportée :D

J'ai cependant un problème, identique à la dernière fois.

tcpdump montre bien mon traffic arriver sur eth0, mais il n'apparait pas sur gt-tun0.

Tout semble ok dans /etc/shorewall/shorewall.conf, y'a t'il eu d'autre modifications apportées sur ce point ?

**Comment by kevimax** [comment]
Bonjour @Ysurac , Bonjour à tous,

Je n'avance pas sur le problème, je fais appel à vos competences 👍 

J'ai complètement suppprimé les modules nf_conntrack_sip et nf_nat_sip, ils n'apparaissent plus avec lsmod, ne sont pas chargés, etc..., malgré tout, le traffic SIP entrant (le traffic sortant est OK) est bloqué. 

Il apparait bien sur eth0 du VPS, mais il est filtré du reste des packets SIP sur gt-tun0. Je ne parviens pas a comprendre ce qui peut bloquer..

Les packets "ESTABLISHED", bien sur, passent; en utilisant un autre port, ca passe aussi... il y a donc bien un bloquage sur 5060 entrant..

Etrange non ? 😶‍🌫️
