### ISSUE TITLE
VPS on Pi4?

### ISSUE THREAD

**Issue by hairy-dog** [Ysurac/openmptcprouter-vps#67]
A company is offering hosting in a data centre, running on a Pi4. This would be a lot cheaper than the VPS I am using at present, but would it be as good? Would it work at all?

Separate question: this offering only has IP6 connectivity with some sort of workaround (which I don't understand*) to provide access via IP4. My internet connections all seem to be IP4 only. Would this prevent it working for me?

*They say "We expose SSH over IPv4 via a gateway server, and the service includes access to our IPv4-to-v6 proxy, allowing you to host websites on an IPv6-only server."

Sorry if this is a silly question: I don't properly understand how IP6 works because I've never had access to IP6 connections.

**Comment by Ysurac** [comment]
VPS script work only on x86_64. To work on RPI4 VPS kernel would need to be compiled for RPI4.
You need IPv6 internet connections to work with an IPv6 only VPS. We can't use the IPv4-to-IPv6 proxy they provide (as I think it's a simple http proxy as often, else they would provide also an IPv4).

**Comment by hairy-dog** [comment]
Thank you. I suspected that would be the answer!
