### ISSUE TITLE
Question: is it possible to add your script on root crontab

### ISSUE THREAD

**Issue by KoRnEr007** [Ysurac/openmptcprouter-vps#7]
Hello,
just to know is it possible to put your script on the root crontab to be sure to have the last update of your script ?
Maybe one time per week ?

Thanks by advance
Merci
Jon ;)

**Comment by Ysurac** [comment]
Not possible and not really a good idea. Sometimes changes in VPS scripts may need a new OpenMPTCProuter version.

**Comment by KoRnEr007** [comment]
ok merci pour le support
