### ISSUE TITLE
can't ssh after installation

### ISSUE THREAD

**Issue by mahdiyari** [Ysurac/openmptcprouter-vps#71]
I can ssh through the console from the VPS provider but I can't connect from anywhere else. I did change the ssh port to 22 and tried `iptables -A INPUT -p tcp --dport 22 -j ACCEPT` but didn't help. Then tried killing all the VPNs etc and didn't help. I couldn't kill the one listening on 65500.
Can't even telnet the port 22.

The VPS has some limitations and some websites are blocked. Can't for example `curl https://github.com`. I did install the VPS script by running a VPN on the server. I did edit the .sh script and put server's public ip in both `VPS_DOMAIN` and `VPS_PUBLIC_IP` before running it.
```
VPS_DOMAIN="11.11.11.11"
VPS_PUBLIC_IP="11.11.11.11"
```

Is the problem because I used a vpn for installation?

Also, I did confirm by netstat that the vps is listening on 0.0.0.0:22

**Comment by mahdiyari** [comment]
And on the router side it can't connect to the VPS
```
OMR-VPS: Can't get Server1 token, try later (can't ping server Server1 on 11.11.11.11, no server API answer on 11.11.11.11)
```

**Comment by Ysurac** [comment]
As indicated in the documentation and at the end of the script, SSH port is modified to 65222 after install.
Firewall configuration is managed by shorewall.

**Comment by mahdiyari** [comment]
65222 wasn't working either.

I did notice just right after rebooting I can ssh but it gets blocked after few seconds.

**Comment by Ysurac** [comment]
Check that your VPS provider doesn't have a firewall by default like AWS or GCP.
You may get access before firewall is loaded.

**Comment by mahdiyari** [comment]
There is a firewall but I did disable that (allow everything).

**Comment by Ysurac** [comment]
So modify shorewall configuration in /etc/shorewall/rules. By default only ports 65000-65535 are open.

**Comment by mahdiyari** [comment]
Oh I can't ping 1.1.1.1 from the server.

ping: send msg: operation not permitted

**Comment by Ysurac** [comment]
Check that the good interface to Internet was detected by install script in  /etc/shorewall/params.net

**Comment by mahdiyari** [comment]
Yeah that's the problem. It got the interface of the VPN which was active during installation. So just edit that?

**Comment by Ysurac** [comment]
yes and restart shorewall

**Comment by mahdiyari** [comment]
The router connected immediately after restarting the shorewall. Thank you very much.

**Comment by mahdiyari** [comment]
BTW how can I edit the DNSs on the router? omr-test-speed can't ping any domain because there's no DNS. I can't ping google.com either but can ping the IP.

**Comment by Ysurac** [comment]
In Network->DHCP&DNS
By default, DNS root server are used.
