### ISSUE TITLE
I updated on my VPS: new keys have been generated

### ISSUE THREAD

**Issue by KoRnEr007** [Ysurac/openmptcprouter-vps#8]
Hello,
I just try to update my VPS but new keys have been generated.

I don't know why...

Jon

**Comment by Ysurac** [comment]
From what version to what version ?

**Comment by Ysurac** [comment]
I just fixed update for Scaleway VPS (or any VPS that use /etc/motd.head and not motd)

**Comment by KoRnEr007** [comment]
yes i have see error with motd... i have to update again ?

**Comment by Ysurac** [comment]
No, but when you have errors it's always better to give them if you want the issue to be solved.
Should be ok now (even if you may have key generated again next time).

**Comment by KoRnEr007** [comment]
but i have to update my new keys on my router ?

**Comment by Ysurac** [comment]
yes, else nothing can connect to the VPS.

**Comment by KoRnEr007** [comment]
ok, i have to restart before. My old keys work for the moment.
