### ISSUE TITLE
0.1029-test missing patch

### ISSUE THREAD

**Issue by Kalimeiro** [Ysurac/openmptcprouter-vps#81]
Hi,

When apply patch for DSVPN, we have a missing file terminated by a 404 error and the install script stop.

https://github.com/Ysurac/openmptcprouter-feeds/raw/develop/dsvpn/patches/nofirewall.patch

**Comment by Llorx** [comment]
Just modify this: https://github.com/Ysurac/openmptcprouter-vps/pull/83/commits

**Comment by domdorn** [comment]
just had the same problem..
@Ysurac is there anything preventing you from merging https://github.com/Ysurac/openmptcprouter-vps/commit/a606833b7dc98486ba1950db8bbfefcae4b5d293 into develop so the next person does not run into this problem?

**Comment by Ysurac** [comment]
It was fixed on server since a long time but not in repo. Done.
