### ISSUE TITLE
problème installation sur debian 12

### ISSUE THREAD

**Issue by Henrb** [Ysurac/openmptcprouter-vps#86]
![image](https://github.com/Ysurac/openmptcprouter-vps/assets/88949192/17490a56-f34e-46fd-bcd1-f45f6538d665)

**Comment by Henrb** [comment]
Bonjour , quelqu'un a t-il une réponse a mon problème d'installation sur debian 12, sur le script il est noté que le support debian 12 a été ajouter le week end dernier sur le script du vps  . bonne journée 
Hello, does anyone have an answer to my installation issue on Debian 12? The script mentions that support for Debian 12 was added to the VPS script last weekend. Have a great day!

**Comment by Ysurac** [comment]
Le support fonctionne avec le kernel 6.1 (donc avec UPSTREAM6="yes"), je n'ai pas encore testé en kernel 5.4.

**Comment by Henrb** [comment]
Ok merci pour la réponse, j'avais effectivement pris le kernel par default.
j'ai réinstaller mon vps pour repartir de 0 et réinstaller proprement, en prenant cet fois le kernel 6.1 comme mentionné. voici la nouvelle erreur avec mon kernel, pour faire fonctionner le script je prend le script "debian9-x86_64.sh" sur mon vps car la commande donnée avec le lien de OpenMPTCP me dit que debian 12 n'est pas compatible. ++ l'image 
![image](https://github.com/Ysurac/openmptcprouter-vps/assets/88949192/dc9f439a-449c-4524-8ebd-94131ec40806)

**Comment by Henrb** [comment]
ok , super , merci @Ysurac pour la réponse rapide !! effectivement sans le bon lien cela marche beaucoup moins bien, ou nettement mieux avec le bon lien lol, donc j'ai installé sur un VPS debian 12 IONOS (le moins chère) qui n'est d'ailleurs pas référencer dans la doc, dommage car il marche bien et n'est pas limité enfin de se que je vois pour l'instant. Donc IONOS VPS Server et en client OpenMPTCP je l'ai déployer en VM sur mon NAS DIY (true nas scale sur un pc monter par moi même), pour la connexion internet je n'utilise pas l'agrégation en tout cas pas pour le moment, on verra quand j'aurais la fibre. J'ai Starlink en FAI, donc ta solution est vraiment incroyable marche déjà super bien et est développer régulièrement. Je m'en sert donc pour ouvrir les ports avec Starlink qui en FAI et pour le moment en CG-NAT. Merci pour la solution OpenMPTCP, je trouve vraiment que c'est un travail incroyable je t'encourage, en plus tu répond rapidement. 
Si j'ai besoin je ferais remonter en ticket, je te tiens au courant si tous se passe bien avec VPS debian 12 et OpenMPTCP en VM.  Bon week-end de la fête de la musique. 💯

**Comment by Ysurac** [comment]
attention avec un VPS en 6.1 il faut utiliser aussi le routeur en 6.1 : https://snapshots.openmptcprouter.com/6.1/
(ça peut fonctionner un routeur en 5.4 avec VPS en 6.1, mais pas toujours et je n'ai pas testé depuis longtemps)
